### PR TITLE
Add NET Standard 2.0 support using ManagementClient & ConnectionString

### PR DESCRIPTION
**Pull request by yassinebennani**
Hello,

I added support for the .net standard 2.0 using just a connection string, can you please review the code and see if it's fine. 

Thank you.

### CODE REVIEW

**Comment by niemyjski** [comment]
@yassinebennani sorry for the delay! And thanks for the changes. Have you been able to test this at all? I'll test it hopefully over the weekend if I get some time. Did you take any of these changes from the branch we have for this?

Also would you please mind signing the CLA so we can accept the pr.

**Comment by yassinebennani** [comment]
> @yassinebennani can you please sign the CLA so we can get this merged in.

@niemyjski  Sorry for the delay, yes all tests are passed on my machine, I'm trying to sign the CLA but I have strange behavior, When I click on the link I get (You have signed the CLA for FoundatioFx/Foundatio.AzureServiceBus), I do a recheck and it still (not signed yet)

Any idea ?? 

Thanks

**Comment by dustinchilson** [comment]
This looks awesome just what I've been looking for.

@yassinebennani did you add the email address from the commit to your github account?

**Comment by yassinebennani** [comment]
@dustinchilson Thank you I have checked the commit with adding .patch to the commit' url, it was pushed with my professional email, so I added it and signed the CLA.

Thanks

**Comment by niemyjski** [comment]
Awesome Thanks!!!!

**Comment by yassinebennani** [comment]
> Awesome Thanks!!!!
@niemyjski 
Please can you provide us a new nuget package, with this update ?

Thanks.

**Comment by niemyjski** [comment]
@yassinebennani The unit tests are failing for me locally when I run them and so I'm trying to find the time to look into it further, regardless you can get the nightly builds if any package here: https://myget.org/gallery/exceptionless

**Pull request merged**
